<a href="https://colab.research.google.com/github/IsraelAbebe/Personal-Projects-and-Exercises/blob/master/AIMS-Assignments/Deep-Learning/ExerciseOne.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

# Question 1

In [0]:
a = torch.full((13,13),1)
a[:,[1,6,11]],a[[1,6,11],:] = 2,2
a[2:4,2:4],a[8:10,2:4],a[2:4,8:10],a[8:10,8:10] = 3,3,3,3 
a

tensor([[1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 3., 3., 1., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 3., 3., 1., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [1., 2., 3., 3., 1., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 3., 3., 1., 1., 2., 1., 3., 3., 1., 2., 1.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [1., 2., 1., 1., 1., 1., 2., 1., 1., 1., 1., 2., 1.]])

# Question 2

In [0]:
import torch
from time import perf_counter 

matrix1,matrix2 = torch.empty((500,500)).normal_(0.5,1),torch.randn((500,500)).normal_(0.5,1)

In [0]:
# %%time
t1_start = perf_counter()
result = torch.mul(matrix1,matrix2)
t1_stop = perf_counter() 

print("Elapsed time during the whole program in seconds:", 
                                        t1_stop-t1_start) 

Elapsed time during the whole program in seconds: 0.0008092359999949394


# Question 3

In [0]:
def mul_row2(input_tensor):
    for i in range(input_tensor.size(0)):
        for j in range(input_tensor.size(1)):
            input_tensor[i,j] =  torch.mul(i+1,input_tensor[i,j])

    return input_tensor

def mul_row(input_tensor):
    for i in range(input_tensor.size(0)):
            input_tensor[i] =  torch.mul(i+1,input_tensor[i])
    return input_tensor

def mul_row_fast(input_tensor):
    n = input_tensor.size(0)
    input_tensor = torch.mul(torch.arange(1,n+1,1).view(n,-1),input_tensor)
    return input_tensor

In [0]:
m = torch.full((4,8),2.0)
print(m)
mul_row(m)


tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])


tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [0]:

m = torch.full((4,8),2.0)
print(m)
mul_row_fast(m)

tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2.]])


tensor([[2., 2., 2., 2., 2., 2., 2., 2.],
        [4., 4., 4., 4., 4., 4., 4., 4.],
        [6., 6., 6., 6., 6., 6., 6., 6.],
        [8., 8., 8., 8., 8., 8., 8., 8.]])

In [0]:
matrix1= torch.empty((1000,400)).normal_(0.5,1)
t1_start = perf_counter()
result = mul_row(matrix1)
t1_stop = perf_counter() 

print("Elapsed time during the whole program in seconds:", 
                                        t1_stop-t1_start) 

Elapsed time during the whole program in seconds: 0.01606515000000286


In [0]:
matrix1= torch.empty((1000,400)).normal_(0.5,1)
t1_start = perf_counter()
result = mul_row_fast(matrix1)
t1_stop = perf_counter() 

print("Elapsed time during the whole program in seconds:", 
                                        t1_stop-t1_start) 

Elapsed time during the whole program in seconds: 0.0012700510000058784


# Multilayer MNIST

# Data

Getting dataset from google drive

If you are testing on your machine skip this step and import.

```
    from dlc_practical_prologue import *
```

In [0]:
import torch
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
!unzip drive/My\ Drive/data/data.zip 
# ls

Archive:  drive/My Drive/data/data.zip
   creating: data/
   creating: data/mnist/
   creating: data/mnist/raw/
  inflating: data/mnist/raw/train-images-idx3-ubyte  
  inflating: data/mnist/raw/train-labels-idx1-ubyte  
  inflating: data/mnist/raw/t10k-images-idx3-ubyte  
  inflating: data/mnist/raw/t10k-labels-idx1-ubyte  
   creating: data/mnist/processed/
  inflating: data/mnist/processed/training.pt  
  inflating: data/mnist/processed/test.pt  
   creating: data/mnist/MNIST/
   creating: data/mnist/MNIST/raw/
  inflating: data/mnist/MNIST/raw/train-images-idx3-ubyte  
  inflating: data/mnist/MNIST/raw/train-labels-idx1-ubyte  
  inflating: data/mnist/MNIST/raw/t10k-images-idx3-ubyte  
  inflating: data/mnist/MNIST/raw/t10k-labels-idx1-ubyte  
   creating: data/mnist/MNIST/processed/
  inflating: data/mnist/MNIST/processed/training.pt  
  inflating: data/mnist/MNIST/processed/test.pt  
   creating: data/cifar10/
  inflating: data/cifar10/cifar-10-python.tar.gz  
   creating: data/ci

In [0]:
import torch
from dlc_practical_prologue import *

In [0]:
data = load_data(one_hot_labels=True,normalize=True)

* Using MNIST


/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:53: UserWarning: train_data has been renamed data
  warnings.warn("train_data has been renamed data")
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:43: UserWarning: train_labels has been renamed targets
  warnings.warn("train_labels has been renamed targets")
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:58: UserWarning: test_data has been renamed data
  warnings.warn("test_data has been renamed data")
/usr/local/lib/python3.6/dist-packages/torchvision/datasets/mnist.py:48: UserWarning: test_labels has been renamed targets
  warnings.warn("test_labels has been renamed targets")


** Reduce the data-set (use --full for the full thing)
** Use 1000 train and 1000 test samples


\begin{aligned}
&\tanh (x)
\\~\\
&\frac{d \tanh (x)}{d x}
\\~\\
&\|t-v\|^{2}
\\~\\
&2 *(t-v)
\end{aligned}


In [0]:
def sigma(inputs):
    return torch.tanh(inputs)

def dsigma(inputs):
    return 1-torch.pow(sigma(inputs),2)

def loss(v,t):
    return torch.pow((v-t),2).sum()

def dloss(v,t):
    return 2*(v-t)

In [0]:
def get_params(train_images,hidden_dim=50,out_dim=10,std = 1e-6):
    w1 = torch.empty((hidden_dim,train_images.size(1))).normal_(0,std)
    b1 = torch.empty((hidden_dim,1)).normal_(0,std)

    w2 = torch.empty((out_dim,hidden_dim)).normal_(0,std)
    b2 = torch.empty((out_dim,1)).normal_(0,std)

    dl_w1 = torch.empty_like(w1)
    dl_b1 = torch.empty_like(b1)

    dl_w2 = torch.empty_like(w2)
    dl_b2 = torch.empty_like(b2)

    return w1,b1,w2,b2,dl_w1,dl_b1,dl_w2,dl_b2

\begin{aligned}
&\begin{array}{l}
{x} \\
{|}
\end{array}\\
&\begin{array}{l}
{w_{1}+x+b_{1}=\left(s_{1}\right)} \\
 \\
{|}
\\
{\sigma\left(s_{1}\right)=x_{1}} \\
 \\
{|}
\\
{w_{2}+x_{1}+b_{2}=\left(s_{2}\right)} \\
 \\
{|}
\\
{\sigma\left(s_{2}\right)=x_{2}} \\
 \\
{|}
\\
{L}
{}
\end{array}
\end{aligned}


In [0]:
def forward_pass(w1,b1,w2,b2,x):
    s1 = torch.add(torch.mm(w1,x),b1)
    x1 = sigma(s1)

    s2 = torch.add(torch.mm(w2,x1),b2)
    x2 = sigma(s2)

    return x,s1,x1,s2,x2


def backward_pass(w1,b1,w2,b2,t,x,s1,x1,s2,x2,dl_dw1,dl_db1,dl_dw2,dl_db2):
    dl_dx2 = dloss(x2,t)
    dl_ds2 = dl_dx2*dsigma(s2)

    dl_dw2.add_(torch.mm(dl_ds2,x1.view(1,-1)))
    dl_db2.add_(dl_ds2)

    dl_dx1 = torch.mm(w2.T,dl_ds2)
    dl_ds1 = dl_dx1*dsigma(s1)

    dl_dw1.add_(torch.mm(dl_ds1,x.view(1,-1)))
    dl_db1.add_(dl_ds1)

In [0]:
train_images,train_labels,test_images,test_labels = data

w1,b1,w2,b2,dl_dw1,dl_db1,dl_dw2,dl_db2 = get_params(train_images,hidden_dim=50,out_dim=10)

train_labels,test_labels = train_labels * 0.9,test_labels * 0.9
train_images,train_labels = train_images * 0.9,train_labels * 0.9

train_size = len(train_images)
test_size = len(test_images)

lr = 1e-1 / train_size
epoch = 1000

for i in range(epoch):
    dl_dw1.zero_()
    dl_db1.zero_()
    dl_dw2.zero_()
    dl_db2.zero_()

    correct_count = 0
    test_correct_count = 0
    running_loss = 0

    for image,labels in zip(train_images,train_labels):
        x,s1,x1,s2,x2 = forward_pass(w1,b1,w2,b2,image.view(-1,1))
        running_loss += loss(x2,labels.view(-1,1))
        backward_pass(w1,b1,w2,b2,labels.view(-1,1),image.view(-1,1),s1,x1,s2,x2,dl_dw1,dl_db1,dl_dw2,dl_db2)

    w1 = w1 -  lr * dl_dw1
    b1 = b1 -  lr * dl_db1
    w2 = w2 -  lr * dl_dw2
    b2 = b2 -  lr * dl_db2

    for img,lbl in zip(train_images,train_labels):
        _,_,_,_,x2 = forward_pass(w1,b1,w2,b2,img.view(-1,1))
        if x2.max(0)[1].item()==lbl.max(0)[1].item():
            correct_count +=1

    for t_img,t_lbl in zip(test_images,test_labels):
        _,_,_,_,t_x2 = forward_pass(w1,b1,w2,b2,t_img.view(-1,1))
        if t_x2.max(0)[1].item()==t_lbl.view(-1,1).max(0)[1].item():
            test_correct_count +=1
    
    if i%100 == 0:
        print('Epoch: {}, Loss: {:.02f} Train Accuracy(Error Rate): {:.02f}({:.02f}) , Test Accuracy(Error Rate): {:.02f}({:.02f})'.format(i,running_loss,\
            correct_count/train_size,1-(correct_count/train_size),test_correct_count/test_size,1-(test_correct_count/test_size)))

Epoch: 0, Loss: 656.10 Train Accuracy(Error Rate): 0.12(0.88) , Test Accuracy(Error Rate): 0.10(0.90)
Epoch: 100, Loss: 299.96 Train Accuracy(Error Rate): 0.80(0.20) , Test Accuracy(Error Rate): 0.73(0.27)
Epoch: 200, Loss: 190.84 Train Accuracy(Error Rate): 0.92(0.08) , Test Accuracy(Error Rate): 0.82(0.18)
Epoch: 300, Loss: 137.80 Train Accuracy(Error Rate): 0.95(0.05) , Test Accuracy(Error Rate): 0.82(0.18)
Epoch: 400, Loss: 104.82 Train Accuracy(Error Rate): 0.97(0.03) , Test Accuracy(Error Rate): 0.84(0.16)
Epoch: 500, Loss: 83.16 Train Accuracy(Error Rate): 0.98(0.02) , Test Accuracy(Error Rate): 0.84(0.16)
Epoch: 600, Loss: 83.80 Train Accuracy(Error Rate): 0.99(0.01) , Test Accuracy(Error Rate): 0.83(0.17)
Epoch: 700, Loss: 65.43 Train Accuracy(Error Rate): 0.99(0.01) , Test Accuracy(Error Rate): 0.83(0.17)
Epoch: 800, Loss: 50.46 Train Accuracy(Error Rate): 1.00(0.00) , Test Accuracy(Error Rate): 0.83(0.17)
Epoch: 900, Loss: 51.76 Train Accuracy(Error Rate): 1.00(0.00) , Test 